pool:
  vmImage: 'Ubuntu-16.04'

trigger:
  batch: true
  branches:
    include:
    - develop
    - master 
  paths:
    include:
    - src/admin.ui/*

variables:
  imageName: 'leadtest'
  artifactType: 'container'
  projectPath: './src/admin.ui/admin.ui'
  #prod builds
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    buildVersion: '1.0.0.$(Build.BuildId)'
    buildVersionTag: '1.0.0.$(Build.BuildId)-rc'
    buildTag: 'master'
    registryConnectionName: 'container-crlasoprev'
  #non-prod builds
  ${{ if ne(variables['Build.SourceBranchName'], 'master') }}:
    buildVersion: '1.0.0.$(Build.BuildId)-pre'
    buildVersionTag: '1.0.0.$(Build.BuildId)-pre'
    buildTag: 'develop'
    registryConnectionName: 'container-crlasodev'
  
steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $buildState = @{}
      $buildState.Date= Get-Date  -format yyyy-MM-ddTHH-mm-ss-ff
      $buildState.BuildVersion= "$(buildVersion)"
      $buildState.BuildVersionTag ="$(buildVersionTag)"
      $buildState.ImageName = "$(imageName)"
      $buildState.BuildTag = "$(buildTag)"
      $buildState.ArtifactType= "$(artifactType)"
      $buildState.Build = @{}
      $buildState.Build.URI =  '$(Build.BuildUri)'
      $buildState.Build.BuildId =  '$(Build.BuildId)'
      $buildState.Build.BuildNumber =  '$(Build.BuildNumber)'
      $buildState.Build.DefinitionName =  '$(Build.DefinitionName)'
      $buildState.Build.QueuedBy =  '$(Build.QueuedBy)'
      $buildState.Build.SourceVersion =  '$(Build.SourceVersion)'
      $buildState.Build.SourceBranchName =  '$(Build.SourceBranchName)'
      $buildState.Build.RepoURI =  '$(Build.Repository.Uri)'
      $buildState | ConvertTo-Json -depth 100 | Out-File "$(Build.ArtifactStagingDirectory)\buildState.json"
    pwsh: true
- bash: |
      echo "##vso[build.addbuildtag]$(buildTag)"
- task: Docker@2
  displayName: 'login to $(registryConnectionName)'
  inputs:
    containerRegistry: '$(registryConnectionName)'
    command: 'login'
- task: Docker@2
  displayName: 'build container'
  inputs:
    containerRegistry: '$(registryConnectionName)'
    repository: '$(imageName)'
    command: 'build'
    Dockerfile: '$(projectPath)/Dockerfile'
    buildContext: '$(Build.Repository.LocalPath)/src'
    tags: |
      $(Build.BuildId)
      $(buildVersionTag)
    arguments: '--build-arg  buildVersion=$(buildVersion)'
- task: Docker@2
  displayName: 'push to $(registryConnectionName)'
  inputs:
    containerRegistry: '$(registryConnectionName)'
    repository: '$(imageName)'
    command: 'push'
    tags: |
      $(Build.BuildId)
      $(buildVersionTag)

- task: PublishBuildArtifacts@1
  displayName: Publish Artifacts
  condition: succeeded()
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'

